/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.conflict.jdkclass;

import javax.xml.xpath.XPathFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    // java -Djaxp.debug
    public static void main(String[] args) {
        XPathFactory.newInstance().newXPath();
        System.out.println(new App().getGreeting());
    }
}
