/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.conflict.jdkclass;

import java.util.HashMap;
import java.util.Map;

import javax.xml.xpath.XPathFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    // java -Djaxp.debug
    public static void main(String[] args) {
        Map<String, Long> m = new HashMap<>();
        Long sum = m.values().stream().reduce(0L, Long::sum);
        XPathFactory.newInstance().newXPath();
        System.out.println(new App().getGreeting());
    }
}
